# Generated by Django 5.2.3 on 2025-07-07 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=50)),
                ('point', models.IntegerField()),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='imgs/')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('shops_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField()),
                ('current_true', models.BooleanField(default=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppings.accounts')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppings.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='shops_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppings.shops'),
        ),
    ]
